cs_lib = {
    "alignment_def" : {
        "definition" : """A typical creature in the worlds of DUNGEONS&
                            DRAGONS has an alignment, which broadly describes
                            its moral and personal attitudes. Alignment is a
                            combination of two factors: one identifies morality
                            (good, evil, or neutral),and the other describes
                            altitudes toward society and order (lawful, chaotic,
                            or neutral). Thus, nine distinct alignments define the
                            possible combinations.
                            These brief summaries of the nine alignments
                            describe the typical behavior of a creature with that
                            alignment. Individuals might vary significantly from
                            that typical behavior, and few people are perfectly and
                            consistently faithful to the precepts of their alignment.
                            """,
            "lawful_good" : "Creatures can be counted on to do the right thing as expected by society. Gold dragons, paladins, and most dwarves are lawful good.",
            "neutral_good" : "Folk do the best they can to help others according to their needs. Many celestials, some cloud giants, and most gnomes are neutral good.",
            "chaotic_good" : "Creatures act as their conscience directs, with little regard for what others expect. Copper dragons, many elves, and unicorns are chaotic good.",
            "Lawful_neutral" :"Individuals act in accordance with law, tradition, or personal codes. Many monks and some wizards are lawful neutral.",
            "neutral" : "Is the alignment of those who prefer to steer e1ear of moral questions and don't take sides,doing what seems best at the time. Lizardfolk, most druids, and many humans are neutral.",
            "chaotic_neutral" : "Creatures follow their whims, holding their personal freedom above ali else. Many barbarians and rogues, and some bards, are chaotic neutral.",
            "lawful_evil" : "Creatures methodically take what they want, within the limits of a code of tradition, loyalty, or order. Devils, blue dragons, and hobgoblins are lawful evil.",
            "neutral_evil" : "Is the alignment of those who do whatever they can get away with, without compassion or qualms. Many drow, some e10ud giants, and yugoloths are neutral evil.",
            "chaotic_evil" : "Creatures act with arbitrary violence, spurred by their greed, hatred, or bloodlust. Demons, red dragons, and orcs are chaotic evil."
    },
    "attrib" : {
            "str" : "Strength",
            "dex" : "Dexterity",
            "con" : "Constitution",
            "int" : "Intelligence",
            "wis" : "Wisdom",
            "cha" : "Charisma"
        },
    "char_dict" : {
        "race" : {
            "human" : "Human",
            "duergar_dwarf" : "Duergar Dwarf",
            "hill_dwarf" : "Hill Dwarf",
            "mountain_dwarf" : "Mountain Dwarf",
            "sun_elf" : "Sun Elf",
            "wood_elf" : "Wood Elf",
            "dark_elf" : "Dark Elf",
            "gold_dragonborn" : "Gold Dragonborn",
            "silver_dragonborn" : "Silver Dragonborn",
            "Copper_dragonborn" : "Copper Dragonborn",
            "brass_dragonborn" : "Brass Dragonborn",
            "bronze_dragonborn" : "Bronze Dragonborn",
            "red_dragonborn" : "Red Dragonborn",
            "black_dragonborn" : "Black Dragonborn",
            "blue_dragonborn" : "Blue Dragonborn",
            "green_dragonborn" : "Green Dragonborn",
            "white_dragonborn" : "White Dragonborn",
            "forest_gnome" : "Forest Gnome",
            "rock_gnome" : "Rock Gnome",
            "half_elf" : "Half Elf",
            "half_orc" : "Half Orc",
            "lightfoot_halfling" : "Lightfoot Halfling",
            "Stout_halfling" : "Stout Halfling",
            "tiefling" : "Tiefling"
        },
        "class" : {
            "artificer" : "Artificer",
            "barbarian" : "Barbarian",
            "bard" : "Bard",
            "cleric" : "Cleric",
            "druid" : "Druid",
            "fighter" : "Fighter",
            "monk" : "Monk",
            "paladin" : "Paladin",
            "ranger" : "Ranger",
            "rogue" : "Rogue",
            "sorcerer" : "Sorcerer",
            "warlock" : "Warlock",
            "wizard" : "Wizard"
        },
        "background" : {
            "acolyte" : "Acolyte",
            "charlatan" : "Charlatan",
            "criminal" : "Criminal",
            "entertainer" : "Entertainer",
            "folk_hero" : "Folk Hero",
            "guild_artisan" : "Build Artisan",
            "hermit" : "Hermit",
            "noble" : "Noble",
            "outlander" : "Outlander",
            "sailor" : "Sailor",
            "soldier" : "Soldier",
            "urchin" : "Urchin"
        },
        "alignment" : {
            "law_good" : "Lawful Good",
            "law_neutral" : "Lawful Neutral",
            "law_evil" : "Lawful Evil",
            "neut_good" : "Neutral Good",
            "neut_neutral" : "Neutral Neutral",
            "neut_evil" : "Neutral Evil",
            "chaotic_good" : "Chaotic Good",
            "chaotic_neutral" : "Chaotic Neutral",                                    
            "chaotic_evil" : "Chotic Evil"  
        },
        "savs" : {
            "str_sav" : " Strength",
            "dex_sav" : " Dexterity",
            "con_sav" : " Constitution",
            "int_sav" : " Intelligence",
            "wis_sav" : " Wisdom",
            "cha_sav" : " Charisma",
        },
        "skills" : [{
            "acrobatics" : [" Acrobatics", "Dex"],
            "animal_handling" : [" Animal Handling", "Wis"],
            "arcana" : [" Arcana", "Int"],
            "athletics" : [" Athletics", "Str"],
            "deception" : [" Deception", "Cha"],
            "history" : [" History", "Int"],
            }, {
            "insight" : [" Insight", "Wis"],
            "intimidation" : [" Intimidation", "Cha"],
            "investigation" : [" Investigation", "Int"],
            "medicine" : [" Medicine", "Wis"],
            "nature" : [" Nature", "Int"],
            "perception" : [" Perception", "Wis"],
            }, {
            "performance" : [" Performance", "Cha"],
            "persuasion" : [" Persuasion", "Cha"],
            "religion" : [" Religion", "Int"],
            "sleight_of_hand" : [" Sleight of Hand", "Dex"],
            "stealth" : [" Stealth", "Dex"],
            "survival" : [" Survival", "Wis"]
            }
        ]
    },
    "skill_prof" : {
        "acrobatics_prof" : "Acrobatics",
        "animal_handling_prof" : "Animal Handling",
        "arcana_prof" : "Arcana",
        "athletics_prof" : "Athletics",
        "deception_prof" : "Deception",
        "history_prof" : "History",
        "insight_prof" : "Insight",
        "intimidation_prof" : "Intimidation",
        "investigation_prof" : "Investigation",
        "medicine_prof" : "Medicine",
        "nature_prof" : "Nature",
        "perception_prof" : "Perception",
        "performance_prof" : "Performance",
        "persuasion_prof" : "Persuasion",
        "religion_prof" : "Religion",
        "sleight_of_hand_prof" : "Sleight of Hand",
        "stealth_prof" : "Stealth",
        "survival_prof" : "Survival",
        },
    "lang_prof" : {
            "common_lang_prof" : "Common",
            "dwarvish_lang_prof" : "Dwarvish",
            "elvish_lang_prof" : "Elvish",
            "giant_lang_prof" : "Giant",
            "gnomish_lang_prof" : "Gnomish",
            "goblin_lang_prof" : "Goblin",
            "halfling_lang_prof" : "Halfling",
            "orc_lang_prof" : "Orc",
            "abyssal_lang_prof" : "Abyssal",
            "celestial_lang_prof" : "Celestial",
            "draconic_lang_prof" : "Draconic",
            "deepspeech_lang_prof" : "Deepspeech",
            "infernal_lang_prof" : "Infernal",
            "primordial_lang_prof" : "Primordial",
            "sylvan_lang_prof" : "Sylvan",
            "undercommon_lang_prof" : "Undercommon"
        },
    "armor_prof" : {
        "heavy_armor_prof" : "Heavy Armor",
        "medium_armor_prof" : "Medium Armor",
        "light_armor_prof" : "Light Armor",
        "shields_prof" : "Shields"
        },
    "source" : {
        "hmb" : "HomeBrew",
        "AAG" : "Astral Adventures Guide",
        "BGDA" : "Balder's Gate: Descent into Avernus",
        "DMG" : "Dungeon Master's Guide",
        "EGW" : "Explorer's Guide to WildeMount",
        "ERLW" : "Eberron Rising from the Last War",
        "IDRF" : "Icewind Dale: Rime of the Frostmaiden",
        "JTRC" : "Journeys through the Radiant Citadel",
        "MTOF" : "Mordenkainen's Tome of Foes",
        "OOTA" : "Out of the Abyss",
        "PHB" : "Player's Handbook",
        "SCAG" : "Sword Coast Adventures Guide",
        "SCC" : "Strixhaven: A Curriculum of Chaos",
        "TOA" : "Tomb of Annihilatioin",
        "VGM" : "Volo's Guide to Monsters",
        "VRGR" : "Van Richten's Guide to Ravenloft",
        "WBTW" : "The Wild Beyond the Witchlight",
        "WDH" : "WaterDeep: Dragon Heist",
        "WDMM" : "WaterDeep: Dungeon of the Mad Mage",
        "XGE" : "Xanathar's Guide to Everything",
        "TCE" : "Tasha's Cauldron of Everything"
    },
    "weapon_prof" : {
        "simple_weapons_prof" : "Simple Weapons",
        "martial_weapons_prof" : "Martial Weapons",
        "sword_prof" : "Swords",
        "axe_prof" : "Axes",
        "bow_prof" : "Bows",
        "pole_prof" : "Pole Arms",
        "warhammer_prof" : "War Hammers"
        },
    "weapon_type" : {
        "club_prof" : "Club",
        "dagger_prof" : "Dagger",
        "greatclub_prof" : "Greatclub",
        "handaxe_prof" : "Handaxe",
        "javelin_prof" : "Javelin",
        "light_hammer_prof" : "Light Hammer",
        "mace_prof" : "Mace",
        "quarterstaff_prof" : "Quarterstaff",
        "sickle_prof" : "Sickle",
        "spear_prof" : "Spear",
        "unarmed_strike_prof" : "Unarmed Strike",
        "light_crossbow_prof" : "Light Crossbow",
        "dart_prof" : "Dart",
        "shortbow_prof" : "Shortbow",
        "sling_prof" : "Sling",
        "battleaxe_prof" : "Battleaxe",
        "flail_prof" : "Flail",
        "glaive_prof" : "Glaive",
        "greateaxe_prof" : "Greateaxe",
        "greatsword_prof" : "Greatsword",
        "halberd_prof" : "Halberd",
        "lance_prof" : "Lance",
        "longsword_prof" : "Longsword",
        "maul_prof" : "Maul",
        "morningstar_prof" : "Morningstar",
        "pike_prof" : "Pike",
        "rapier_prof" : "Rapier",
        "scimitar_prof" : "Scimitar",
        "shortsword_prof" : "Shortsword",
        "trident_prof" : "Trident",
        "war_pick_prof" : "War_pick",
        "warhammer_prof" : "Warhammer",
        "whip_prof" : "Whip",
        "blowgun_prof" : "Blowgun",
        "crossbow_hand_prof" : "Crossbow, Hand",
        "crossbow_heavy_prof" : "Crossbow, Heavy",
        "longbow_prof" : "Longbow",
        "net_prof" : "Net"
    },
    "weap_choice" : [
        "weapon_prof1",
        "weapon_prof2",
        "weapon_prof3",
        "weapon_prof4"
    ],
    "armor_choice" : [
        "armor_prof1",
        "armor_prof2",
        "armor_prof3"        
    ],
    "tool_type" : {
        "artisans_tools" : "Artisan's Tools",
        "gaming_set" : "Gaming Set",
        "instrument" : "Instrument",
        "vehicle" : "Vehicle",
        "vehicle_land" : "Vehicle (Land)",
        "vehicle_water" : "Vehicle (water)"
    },
}